### ISSUE TITLE
First version based on DDS template

### ISSUE THREAD

**Issue by FRosner** [FRosner/nefarious-flare#1]
**Build**
- [x] copy and clean up DDS https://github.com/FRosner/spawncamping-dds

**Spark Back-End**
- Reuse one Spark Context or spin up a new one for each execution?
- http://techblog.net-a-porter.com/2013/12/ask-tell-and-per-request-actors/ to avoid blocking when spark context is executing?
- Probably good to have a Spark Context actor that is doing the Spark work while the response actor can return an execution result object and is not blocking

**REST API**
- CRUD: http://www.restapitutorial.com/lessons/httpmethods.html

| URI | Method | Action (Response Code) |
| --- | --- | --- |
| `/stages` | GET | return array of all available stages (200) |
| `/stages` | POST | add stage and return location header with link to new id `/stages/<id>` (201) |
| `/stages` | PUT | operation not supported (404) |
| `/stages` | DELETE | delete all stages (200) |
| `/stages/<id>` | GET | stage with given id (200), id is invalid (404) |
| `/stages/<id>` | POST | operation not supported (404) |
| `/stages/<id>` | PUT | update stage with given id (200), id is invalid (404) |
| `/stages/<id>` | DELETE | delete stage with given id (200), id is invalid (404) |

**UI**
- [x] Modal for editing stages (https://angular-ui.github.io/bootstrap/)
- [ ] Components as draggable panels? http://www.bootply.com/dUQiGMggWO + https://jqueryui.com/draggable/#events
- [x] Code editor http://ace.c9.io/#nav=embedding
- [ ] Connecting stages through drag and drop SVG paths (either self made or https://jsplumbtoolkit.com/community/demo/draggableConnectors/index.html)

**ToDo**
- [x] Look at https://github.com/Credera/spray-person#master

**Comment by FRosner** [comment]
http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by FRosner** [comment]
https://angular-ui.github.io/bootstrap/
